//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.12 at 12:48:55 PM PST 
//


package co.launchable.api.viator.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://toursgds.com/api/01}Request">
 *       &lt;sequence>
 *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="DeltaOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DeltaSince" type="{http://toursgds.com/api/01}timezonedDateTime" minOccurs="0"/>
 *         &lt;element name="SupplierProductCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TourOptions" type="{http://toursgds.com/api/01}TourOptions" minOccurs="0"/>
 *         &lt;element name="AvailabilityHold" type="{http://toursgds.com/api/01}AvailabilityHold" minOccurs="0"/>
 *         &lt;element name="TravellerMix" type="{http://toursgds.com/api/01}TravellerMix" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "startDate",
    "endDate",
    "deltaOnly",
    "deltaSince",
    "supplierProductCode",
    "tourOptions",
    "availabilityHold",
    "travellerMix"
})
@XmlRootElement(name = "AvailabilityRequest")
public class AvailabilityRequest
    extends Request
{

    @XmlElement(name = "StartDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "EndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;
    @XmlElement(name = "DeltaOnly")
    protected Boolean deltaOnly;
    @XmlElement(name = "DeltaSince")
    protected XMLGregorianCalendar deltaSince;
    @XmlElement(name = "SupplierProductCode", required = true)
    protected String supplierProductCode;
    @XmlElement(name = "TourOptions")
    protected TourOptions tourOptions;
    @XmlElement(name = "AvailabilityHold")
    protected AvailabilityHold availabilityHold;
    @XmlElement(name = "TravellerMix")
    protected TravellerMix travellerMix;

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the deltaOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeltaOnly() {
        return deltaOnly;
    }

    /**
     * Sets the value of the deltaOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeltaOnly(Boolean value) {
        this.deltaOnly = value;
    }

    /**
     * Gets the value of the deltaSince property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeltaSince() {
        return deltaSince;
    }

    /**
     * Sets the value of the deltaSince property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeltaSince(XMLGregorianCalendar value) {
        this.deltaSince = value;
    }

    /**
     * Gets the value of the supplierProductCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierProductCode() {
        return supplierProductCode;
    }

    /**
     * Sets the value of the supplierProductCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierProductCode(String value) {
        this.supplierProductCode = value;
    }

    /**
     * Gets the value of the tourOptions property.
     * 
     * @return
     *     possible object is
     *     {@link TourOptions }
     *     
     */
    public TourOptions getTourOptions() {
        return tourOptions;
    }

    /**
     * Sets the value of the tourOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TourOptions }
     *     
     */
    public void setTourOptions(TourOptions value) {
        this.tourOptions = value;
    }

    /**
     * Gets the value of the availabilityHold property.
     * 
     * @return
     *     possible object is
     *     {@link AvailabilityHold }
     *     
     */
    public AvailabilityHold getAvailabilityHold() {
        return availabilityHold;
    }

    /**
     * Sets the value of the availabilityHold property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailabilityHold }
     *     
     */
    public void setAvailabilityHold(AvailabilityHold value) {
        this.availabilityHold = value;
    }

    /**
     * Gets the value of the travellerMix property.
     * 
     * @return
     *     possible object is
     *     {@link TravellerMix }
     *     
     */
    public TravellerMix getTravellerMix() {
        return travellerMix;
    }

    /**
     * Sets the value of the travellerMix property.
     * 
     * @param value
     *     allowed object is
     *     {@link TravellerMix }
     *     
     */
    public void setTravellerMix(TravellerMix value) {
        this.travellerMix = value;
    }

}
