//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.12 at 12:48:55 PM PST 
//


package co.launchable.api.viator.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cancellationRejectionReason.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="cancellationRejectionReason">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PAST_CANCEL_DATE"/>
 *     &lt;enumeration value="PAST_TOUR_DATE"/>
 *     &lt;enumeration value="TOUR_REDEEMED"/>
 *     &lt;enumeration value="OTHER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "cancellationRejectionReason")
@XmlEnum
public enum CancellationRejectionReason {

    PAST_CANCEL_DATE,
    PAST_TOUR_DATE,
    TOUR_REDEEMED,
    OTHER;

    public String value() {
        return name();
    }

    public static CancellationRejectionReason fromValue(String v) {
        return valueOf(v);
    }

}
