//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.12 at 12:48:55 PM PST 
//


package co.launchable.api.viator.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import java.lang.*;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.launchable.api.viator.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Parameters_QNAME = new QName("http://toursgds.com/api/01", "Parameters");
    private final static QName _BookingLanguageCode_QNAME = new QName("http://toursgds.com/api/01", "BookingLanguageCode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.launchable.api.viator.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BookingRequestBase }
     * 
     */
    public BookingRequestBase createBookingRequestBase() {
        return new BookingRequestBase();
    }

    /**
     * Create an instance of {@link BookingResponseBase }
     * 
     */
    public BookingResponseBase createBookingResponseBase() {
        return new BookingResponseBase();
    }

    /**
     * Create an instance of {@link BookingRequestBase.RequiredInfo }
     * 
     */
    public BookingRequestBase.RequiredInfo createBookingRequestBaseRequiredInfo() {
        return new BookingRequestBase.RequiredInfo();
    }

    /**
     * Create an instance of {@link ManifestRequest }
     * 
     */
    public ManifestRequest createManifestRequest() {
        return new ManifestRequest();
    }

    /**
     * Create an instance of {@link Extension }
     * 
     */
    public Extension createExtension() {
        return new Extension();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link AvailabilityRequest }
     * 
     */
    public AvailabilityRequest createAvailabilityRequest() {
        return new AvailabilityRequest();
    }

    /**
     * Create an instance of {@link TourOptions }
     * 
     */
    public TourOptions createTourOptions() {
        return new TourOptions();
    }

    /**
     * Create an instance of {@link AvailabilityHold }
     * 
     */
    public AvailabilityHold createAvailabilityHold() {
        return new AvailabilityHold();
    }

    /**
     * Create an instance of {@link TravellerMix }
     * 
     */
    public TravellerMix createTravellerMix() {
        return new TravellerMix();
    }

    /**
     * Create an instance of {@link ManifestResponse }
     * 
     */
    public ManifestResponse createManifestResponse() {
        return new ManifestResponse();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link RequestStatus }
     * 
     */
    public RequestStatus createRequestStatus() {
        return new RequestStatus();
    }

    /**
     * Create an instance of {@link Booking }
     * 
     */
    public Booking createBooking() {
        return new Booking();
    }

    /**
     * Create an instance of {@link BookingRequest }
     * 
     */
    public BookingRequest createBookingRequest() {
        return new BookingRequest();
    }

    /**
     * Create an instance of {@link BookingRequestBase.Inclusions }
     * 
     */
    public BookingRequestBase.Inclusions createBookingRequestBaseInclusions() {
        return new BookingRequestBase.Inclusions();
    }

    /**
     * Create an instance of {@link co.launchable.api.viator.xml.Traveller }
     * 
     */
    public co.launchable.api.viator.xml.Traveller createTraveller() {
        return new co.launchable.api.viator.xml.Traveller();
    }

    /**
     * Create an instance of {@link BookingRequestBase.AdditionalRemarks }
     * 
     */
    public BookingRequestBase.AdditionalRemarks createBookingRequestBaseAdditionalRemarks() {
        return new BookingRequestBase.AdditionalRemarks();
    }

    /**
     * Create an instance of {@link BookingRequestBase.ContactDetail }
     * 
     */
    public BookingRequestBase.ContactDetail createBookingRequestBaseContactDetail() {
        return new BookingRequestBase.ContactDetail();
    }

    /**
     * Create an instance of {@link BookingNotificationRequest }
     * 
     */
    public BookingNotificationRequest createBookingNotificationRequest() {
        return new BookingNotificationRequest();
    }

    /**
     * Create an instance of {@link BatchAvailabilityResponse }
     * 
     */
    public BatchAvailabilityResponse createBatchAvailabilityResponse() {
        return new BatchAvailabilityResponse();
    }

    /**
     * Create an instance of {@link BatchTourAvailability }
     * 
     */
    public BatchTourAvailability createBatchTourAvailability() {
        return new BatchTourAvailability();
    }

    /**
     * Create an instance of {@link SupplierCapabilityRequest }
     * 
     */
    public SupplierCapabilityRequest createSupplierCapabilityRequest() {
        return new SupplierCapabilityRequest();
    }

    /**
     * Create an instance of {@link TourListResponse }
     * 
     */
    public TourListResponse createTourListResponse() {
        return new TourListResponse();
    }

    /**
     * Create an instance of {@link Tour }
     * 
     */
    public Tour createTour() {
        return new Tour();
    }

    /**
     * Create an instance of {@link AvailabilityNotificationRequest }
     * 
     */
    public AvailabilityNotificationRequest createAvailabilityNotificationRequest() {
        return new AvailabilityNotificationRequest();
    }

    /**
     * Create an instance of {@link ChangedAvailability }
     * 
     */
    public ChangedAvailability createChangedAvailability() {
        return new ChangedAvailability();
    }

    /**
     * Create an instance of {@link BookingRedemptionResponse }
     * 
     */
    public BookingRedemptionResponse createBookingRedemptionResponse() {
        return new BookingRedemptionResponse();
    }

    /**
     * Create an instance of {@link RedemptionTransactionStatus }
     * 
     */
    public RedemptionTransactionStatus createRedemptionTransactionStatus() {
        return new RedemptionTransactionStatus();
    }

    /**
     * Create an instance of {@link BookingRedemptionRequest }
     * 
     */
    public BookingRedemptionRequest createBookingRedemptionRequest() {
        return new BookingRedemptionRequest();
    }

    /**
     * Create an instance of {@link BookingCancellationResponse }
     * 
     */
    public BookingCancellationResponse createBookingCancellationResponse() {
        return new BookingCancellationResponse();
    }

    /**
     * Create an instance of {@link CancellationTransactionStatus }
     * 
     */
    public CancellationTransactionStatus createCancellationTransactionStatus() {
        return new CancellationTransactionStatus();
    }

    /**
     * Create an instance of {@link AvailabilityResponse }
     * 
     */
    public AvailabilityResponse createAvailabilityResponse() {
        return new AvailabilityResponse();
    }

    /**
     * Create an instance of {@link TourAvailability }
     * 
     */
    public TourAvailability createTourAvailability() {
        return new TourAvailability();
    }

    /**
     * Create an instance of {@link TourListRequest }
     * 
     */
    public TourListRequest createTourListRequest() {
        return new TourListRequest();
    }

    /**
     * Create an instance of {@link BookingAmendmentResponse }
     * 
     */
    public BookingAmendmentResponse createBookingAmendmentResponse() {
        return new BookingAmendmentResponse();
    }

    /**
     * Create an instance of {@link BookingResponseBase.Traveller }
     * 
     */
    public BookingResponseBase.Traveller createBookingResponseBaseTraveller() {
        return new BookingResponseBase.Traveller();
    }

    /**
     * Create an instance of {@link BookingTransactionStatus }
     * 
     */
    public BookingTransactionStatus createBookingTransactionStatus() {
        return new BookingTransactionStatus();
    }

    /**
     * Create an instance of {@link BookingCancellationRequest }
     * 
     */
    public BookingCancellationRequest createBookingCancellationRequest() {
        return new BookingCancellationRequest();
    }

    /**
     * Create an instance of {@link BookingResponse }
     * 
     */
    public BookingResponse createBookingResponse() {
        return new BookingResponse();
    }

    /**
     * Create an instance of {@link BookingNotificationResponse }
     * 
     */
    public BookingNotificationResponse createBookingNotificationResponse() {
        return new BookingNotificationResponse();
    }

    /**
     * Create an instance of {@link SupplierCapabilityResponse }
     * 
     */
    public SupplierCapabilityResponse createSupplierCapabilityResponse() {
        return new SupplierCapabilityResponse();
    }

    /**
     * Create an instance of {@link ErrorResponse }
     * 
     */
    public ErrorResponse createErrorResponse() {
        return new ErrorResponse();
    }

    /**
     * Create an instance of {@link AvailabilityNotificationResponse }
     * 
     */
    public AvailabilityNotificationResponse createAvailabilityNotificationResponse() {
        return new AvailabilityNotificationResponse();
    }

    /**
     * Create an instance of {@link BatchAvailabilityRequest }
     * 
     */
    public BatchAvailabilityRequest createBatchAvailabilityRequest() {
        return new BatchAvailabilityRequest();
    }

    /**
     * Create an instance of {@link BookingAmendmentRequest }
     * 
     */
    public BookingAmendmentRequest createBookingAmendmentRequest() {
        return new BookingAmendmentRequest();
    }

    /**
     * Create an instance of {@link TourLanguage }
     * 
     */
    public TourLanguage createTourLanguage() {
        return new TourLanguage();
    }

    /**
     * Create an instance of {@link ApiKeySession }
     * 
     */
    public ApiKeySession createApiKeySession() {
        return new ApiKeySession();
    }

    /**
     * Create an instance of {@link TransactionStatus }
     * 
     */
    public TransactionStatus createTransactionStatus() {
        return new TransactionStatus();
    }

    /**
     * Create an instance of {@link TourOptionsBase }
     * 
     */
    public TourOptionsBase createTourOptionsBase() {
        return new TourOptionsBase();
    }

    /**
     * Create an instance of {@link OptionType }
     * 
     */
    public OptionType createOptionType() {
        return new OptionType();
    }

    /**
     * Create an instance of {@link AvailabilityHoldResponse }
     * 
     */
    public AvailabilityHoldResponse createAvailabilityHoldResponse() {
        return new AvailabilityHoldResponse();
    }

    /**
     * Create an instance of {@link BookingLanguage }
     * 
     */
    public BookingLanguage createBookingLanguage() {
        return new BookingLanguage();
    }

    /**
     * Create an instance of {@link UsernamePasswordSession }
     * 
     */
    public UsernamePasswordSession createUsernamePasswordSession() {
        return new UsernamePasswordSession();
    }

    /**
     * Create an instance of {@link AvailabilityStatus }
     * 
     */
    public AvailabilityStatus createAvailabilityStatus() {
        return new AvailabilityStatus();
    }

    /**
     * Create an instance of {@link java.lang.Error }
     * 
     */
    public java.lang.Error createError() {
        return new java.lang.Error();
    }

    /**
     * Create an instance of {@link AvailableTourOptions }
     * 
     */
    public AvailableTourOptions createAvailableTourOptions() {
        return new AvailableTourOptions();
    }

    /**
     * Create an instance of {@link TravellerMixAvailability }
     * 
     */
    public TravellerMixAvailability createTravellerMixAvailability() {
        return new TravellerMixAvailability();
    }

    /**
     * Create an instance of {@link BookingRequestBase.RequiredInfo.Question }
     * 
     */
    public BookingRequestBase.RequiredInfo.Question createBookingRequestBaseRequiredInfoQuestion() {
        return new BookingRequestBase.RequiredInfo.Question();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Parameter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://toursgds.com/api/01", name = "Parameters")
    public JAXBElement<Parameter> createParameters(Parameter value) {
        return new JAXBElement<Parameter>(_Parameters_QNAME, Parameter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://toursgds.com/api/01", name = "BookingLanguageCode")
    public JAXBElement<String> createBookingLanguageCode(String value) {
        return new JAXBElement<String>(_BookingLanguageCode_QNAME, String.class, null, value);
    }

}
