//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.12 at 12:48:55 PM PST 
//


package co.launchable.api.viator.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 *            Tour Details         
 *         
 * 
 * <p>Java class for Tour complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tour">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SupplierProductCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SupplierProductName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Language" type="{http://toursgds.com/api/01}TourLanguage" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TourDepartureTime" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *         &lt;element name="TourDuration" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
 *         &lt;element name="CountryCode" type="{http://toursgds.com/api/01}countryCode"/>
 *         &lt;element name="DestinationCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DestinationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TourDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TourOption" type="{http://toursgds.com/api/01}AvailableTourOptions" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tour", propOrder = {
    "supplierProductCode",
    "supplierProductName",
    "language",
    "tourDepartureTime",
    "tourDuration",
    "countryCode",
    "destinationCode",
    "destinationName",
    "tourDescription",
    "tourOption"
})
public class Tour {

    @XmlElement(name = "SupplierProductCode", required = true)
    protected String supplierProductCode;
    @XmlElement(name = "SupplierProductName", required = true)
    protected String supplierProductName;
    @XmlElement(name = "Language")
    protected List<TourLanguage> language;
    @XmlElement(name = "TourDepartureTime")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar tourDepartureTime;
    @XmlElement(name = "TourDuration")
    protected Duration tourDuration;
    @XmlElement(name = "CountryCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String countryCode;
    @XmlElement(name = "DestinationCode", required = true)
    protected String destinationCode;
    @XmlElement(name = "DestinationName", required = true)
    protected String destinationName;
    @XmlElement(name = "TourDescription", required = true)
    protected String tourDescription;
    @XmlElement(name = "TourOption")
    protected List<AvailableTourOptions> tourOption;

    /**
     * Gets the value of the supplierProductCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierProductCode() {
        return supplierProductCode;
    }

    /**
     * Sets the value of the supplierProductCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierProductCode(String value) {
        this.supplierProductCode = value;
    }

    /**
     * Gets the value of the supplierProductName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierProductName() {
        return supplierProductName;
    }

    /**
     * Sets the value of the supplierProductName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierProductName(String value) {
        this.supplierProductName = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TourLanguage }
     * 
     * 
     */
    public List<TourLanguage> getLanguage() {
        if (language == null) {
            language = new ArrayList<TourLanguage>();
        }
        return this.language;
    }

    /**
     * Gets the value of the tourDepartureTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTourDepartureTime() {
        return tourDepartureTime;
    }

    /**
     * Sets the value of the tourDepartureTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTourDepartureTime(XMLGregorianCalendar value) {
        this.tourDepartureTime = value;
    }

    /**
     * Gets the value of the tourDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getTourDuration() {
        return tourDuration;
    }

    /**
     * Sets the value of the tourDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setTourDuration(Duration value) {
        this.tourDuration = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the destinationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationCode() {
        return destinationCode;
    }

    /**
     * Sets the value of the destinationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationCode(String value) {
        this.destinationCode = value;
    }

    /**
     * Gets the value of the destinationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationName() {
        return destinationName;
    }

    /**
     * Sets the value of the destinationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationName(String value) {
        this.destinationName = value;
    }

    /**
     * Gets the value of the tourDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTourDescription() {
        return tourDescription;
    }

    /**
     * Sets the value of the tourDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTourDescription(String value) {
        this.tourDescription = value;
    }

    /**
     * Gets the value of the tourOption property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tourOption property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTourOption().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AvailableTourOptions }
     * 
     * 
     */
    public List<AvailableTourOptions> getTourOption() {
        if (tourOption == null) {
            tourOption = new ArrayList<AvailableTourOptions>();
        }
        return this.tourOption;
    }

}
