//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.12 at 12:48:55 PM PST 
//


package co.launchable.api.viator.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for API.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="API">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AVAILABILITY"/>
 *     &lt;enumeration value="BATCH_AVAILABILITY"/>
 *     &lt;enumeration value="BOOKING"/>
 *     &lt;enumeration value="BOOKING_AMENDMENT"/>
 *     &lt;enumeration value="BOOKING_CANCELLATION"/>
 *     &lt;enumeration value="BOOKING_REDEMPTION"/>
 *     &lt;enumeration value="TOUR_LIST"/>
 *     &lt;enumeration value="BOOKING_NOTIFICATION"/>
 *     &lt;enumeration value="AVAILABILITY_NOTIFICATION"/>
 *     &lt;enumeration value="BOOKING_MANIFEST"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "API")
@XmlEnum
public enum API {

    AVAILABILITY,
    BATCH_AVAILABILITY,
    BOOKING,
    BOOKING_AMENDMENT,
    BOOKING_CANCELLATION,
    BOOKING_REDEMPTION,
    TOUR_LIST,
    BOOKING_NOTIFICATION,
    AVAILABILITY_NOTIFICATION,
    BOOKING_MANIFEST;

    public String value() {
        return name();
    }

    public static API fromValue(String v) {
        return valueOf(v);
    }

}
