//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.12 at 12:48:55 PM PST 
//


package co.launchable.api.viator.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AvailabilityStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AvailabilityStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Status" type="{http://toursgds.com/api/01}availabilityStatusType"/>
 *         &lt;element name="UnavailabilityReason" type="{http://toursgds.com/api/01}UnavailabilityReason" minOccurs="0"/>
 *         &lt;element name="TravellerMixAvailability" type="{http://toursgds.com/api/01}TravellerMixAvailability" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AvailabilityStatus", propOrder = {
    "status",
    "unavailabilityReason",
    "travellerMixAvailability"
})
public class AvailabilityStatus {

    @XmlElement(name = "Status", required = true)
    protected AvailabilityStatusType status;
    @XmlElement(name = "UnavailabilityReason")
    protected UnavailabilityReason unavailabilityReason;
    @XmlElement(name = "TravellerMixAvailability")
    protected TravellerMixAvailability travellerMixAvailability;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link AvailabilityStatusType }
     *     
     */
    public AvailabilityStatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailabilityStatusType }
     *     
     */
    public void setStatus(AvailabilityStatusType value) {
        this.status = value;
    }

    /**
     * Gets the value of the unavailabilityReason property.
     * 
     * @return
     *     possible object is
     *     {@link UnavailabilityReason }
     *     
     */
    public UnavailabilityReason getUnavailabilityReason() {
        return unavailabilityReason;
    }

    /**
     * Sets the value of the unavailabilityReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnavailabilityReason }
     *     
     */
    public void setUnavailabilityReason(UnavailabilityReason value) {
        this.unavailabilityReason = value;
    }

    /**
     * Gets the value of the travellerMixAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link TravellerMixAvailability }
     *     
     */
    public TravellerMixAvailability getTravellerMixAvailability() {
        return travellerMixAvailability;
    }

    /**
     * Sets the value of the travellerMixAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link TravellerMixAvailability }
     *     
     */
    public void setTravellerMixAvailability(TravellerMixAvailability value) {
        this.travellerMixAvailability = value;
    }

}
