//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.12 at 12:48:55 PM PST 
//


package co.launchable.api.viator.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BookingResponseBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BookingResponseBase">
 *   &lt;complexContent>
 *     &lt;extension base="{http://toursgds.com/api/01}Response">
 *       &lt;sequence>
 *         &lt;element name="BookingReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SupplierCommentCustomer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TourBarcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Traveller" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TravellerIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TravellerSupplierConfirmationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="TravellerSeat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="TravellerBarcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BookingResponseBase", propOrder = {
    "bookingReference",
    "supplierCommentCustomer",
    "tourBarcode",
    "traveller"
})
@XmlSeeAlso({
    BookingResponse.class,
    BookingAmendmentResponse.class
})
public class BookingResponseBase
    extends Response
{

    @XmlElement(name = "BookingReference")
    protected String bookingReference;
    @XmlElement(name = "SupplierCommentCustomer")
    protected String supplierCommentCustomer;
    @XmlElement(name = "TourBarcode")
    protected String tourBarcode;
    @XmlElement(name = "Traveller")
    protected List<BookingResponseBase.Traveller> traveller;

    /**
     * Gets the value of the bookingReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingReference() {
        return bookingReference;
    }

    /**
     * Sets the value of the bookingReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingReference(String value) {
        this.bookingReference = value;
    }

    /**
     * Gets the value of the supplierCommentCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierCommentCustomer() {
        return supplierCommentCustomer;
    }

    /**
     * Sets the value of the supplierCommentCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierCommentCustomer(String value) {
        this.supplierCommentCustomer = value;
    }

    /**
     * Gets the value of the tourBarcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTourBarcode() {
        return tourBarcode;
    }

    /**
     * Sets the value of the tourBarcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTourBarcode(String value) {
        this.tourBarcode = value;
    }

    /**
     * Gets the value of the traveller property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the traveller property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTraveller().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BookingResponseBase.Traveller }
     * 
     * 
     */
    public List<BookingResponseBase.Traveller> getTraveller() {
        if (traveller == null) {
            traveller = new ArrayList<BookingResponseBase.Traveller>();
        }
        return this.traveller;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TravellerIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TravellerSupplierConfirmationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="TravellerSeat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="TravellerBarcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "travellerIdentifier",
        "travellerSupplierConfirmationNumber",
        "travellerSeat",
        "travellerBarcode"
    })
    public static class Traveller {

        @XmlElement(name = "TravellerIdentifier", required = true)
        protected String travellerIdentifier;
        @XmlElement(name = "TravellerSupplierConfirmationNumber")
        protected String travellerSupplierConfirmationNumber;
        @XmlElement(name = "TravellerSeat")
        protected String travellerSeat;
        @XmlElement(name = "TravellerBarcode")
        protected String travellerBarcode;

        /**
         * Gets the value of the travellerIdentifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTravellerIdentifier() {
            return travellerIdentifier;
        }

        /**
         * Sets the value of the travellerIdentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTravellerIdentifier(String value) {
            this.travellerIdentifier = value;
        }

        /**
         * Gets the value of the travellerSupplierConfirmationNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTravellerSupplierConfirmationNumber() {
            return travellerSupplierConfirmationNumber;
        }

        /**
         * Sets the value of the travellerSupplierConfirmationNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTravellerSupplierConfirmationNumber(String value) {
            this.travellerSupplierConfirmationNumber = value;
        }

        /**
         * Gets the value of the travellerSeat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTravellerSeat() {
            return travellerSeat;
        }

        /**
         * Sets the value of the travellerSeat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTravellerSeat(String value) {
            this.travellerSeat = value;
        }

        /**
         * Gets the value of the travellerBarcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTravellerBarcode() {
            return travellerBarcode;
        }

        /**
         * Sets the value of the travellerBarcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTravellerBarcode(String value) {
            this.travellerBarcode = value;
        }

    }

}
