//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.12 at 12:48:55 PM PST 
//


package co.launchable.api.viator.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BookingRequestBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BookingRequestBase">
 *   &lt;complexContent>
 *     &lt;extension base="{http://toursgds.com/api/01}Request">
 *       &lt;sequence>
 *         &lt;group ref="{http://toursgds.com/api/01}BookingBase"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BookingRequestBase", propOrder = {
    "bookingReference",
    "travelDate",
    "supplierProductCode",
    "location",
    "tourOptions",
    "inclusions",
    "currencyCode",
    "amount",
    "traveller",
    "travellerMix",
    "requiredInfo",
    "specialRequirement",
    "pickupPoint",
    "supplierNote",
    "additionalRemarks",
    "contactDetail"
})
@XmlSeeAlso({
    BookingAmendmentRequest.class,
    BookingRequest.class
})
public class BookingRequestBase
    extends Request
{

    @XmlElement(name = "BookingReference", required = true)
    protected String bookingReference;
    @XmlElement(name = "TravelDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar travelDate;
    @XmlElement(name = "SupplierProductCode", required = true)
    protected String supplierProductCode;
    @XmlElement(name = "Location")
    protected String location;
    @XmlElement(name = "TourOptions")
    protected TourOptions tourOptions;
    @XmlElement(name = "Inclusions")
    protected BookingRequestBase.Inclusions inclusions;
    @XmlElement(name = "CurrencyCode")
    protected String currencyCode;
    @XmlElement(name = "Amount")
    protected Double amount;
    @XmlElement(name = "Traveller", required = true)
    protected List<Traveller> traveller;
    @XmlElement(name = "TravellerMix")
    protected TravellerMix travellerMix;
    @XmlElement(name = "RequiredInfo")
    protected BookingRequestBase.RequiredInfo requiredInfo;
    @XmlElement(name = "SpecialRequirement")
    protected String specialRequirement;
    @XmlElement(name = "PickupPoint")
    protected String pickupPoint;
    @XmlElement(name = "SupplierNote")
    protected String supplierNote;
    @XmlElement(name = "AdditionalRemarks")
    protected BookingRequestBase.AdditionalRemarks additionalRemarks;
    @XmlElement(name = "ContactDetail")
    protected BookingRequestBase.ContactDetail contactDetail;

    /**
     * Gets the value of the bookingReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingReference() {
        return bookingReference;
    }

    /**
     * Sets the value of the bookingReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingReference(String value) {
        this.bookingReference = value;
    }

    /**
     * Gets the value of the travelDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTravelDate() {
        return travelDate;
    }

    /**
     * Sets the value of the travelDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTravelDate(XMLGregorianCalendar value) {
        this.travelDate = value;
    }

    /**
     * Gets the value of the supplierProductCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierProductCode() {
        return supplierProductCode;
    }

    /**
     * Sets the value of the supplierProductCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierProductCode(String value) {
        this.supplierProductCode = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the tourOptions property.
     * 
     * @return
     *     possible object is
     *     {@link TourOptions }
     *     
     */
    public TourOptions getTourOptions() {
        return tourOptions;
    }

    /**
     * Sets the value of the tourOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TourOptions }
     *     
     */
    public void setTourOptions(TourOptions value) {
        this.tourOptions = value;
    }

    /**
     * Gets the value of the inclusions property.
     * 
     * @return
     *     possible object is
     *     {@link BookingRequestBase.Inclusions }
     *     
     */
    public BookingRequestBase.Inclusions getInclusions() {
        return inclusions;
    }

    /**
     * Sets the value of the inclusions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookingRequestBase.Inclusions }
     *     
     */
    public void setInclusions(BookingRequestBase.Inclusions value) {
        this.inclusions = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAmount(Double value) {
        this.amount = value;
    }

    /**
     * Gets the value of the traveller property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the traveller property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTraveller().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Traveller }
     * 
     * 
     */
    public List<Traveller> getTraveller() {
        if (traveller == null) {
            traveller = new ArrayList<Traveller>();
        }
        return this.traveller;
    }

    /**
     * Gets the value of the travellerMix property.
     * 
     * @return
     *     possible object is
     *     {@link TravellerMix }
     *     
     */
    public TravellerMix getTravellerMix() {
        return travellerMix;
    }

    /**
     * Sets the value of the travellerMix property.
     * 
     * @param value
     *     allowed object is
     *     {@link TravellerMix }
     *     
     */
    public void setTravellerMix(TravellerMix value) {
        this.travellerMix = value;
    }

    /**
     * Gets the value of the requiredInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BookingRequestBase.RequiredInfo }
     *     
     */
    public BookingRequestBase.RequiredInfo getRequiredInfo() {
        return requiredInfo;
    }

    /**
     * Sets the value of the requiredInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookingRequestBase.RequiredInfo }
     *     
     */
    public void setRequiredInfo(BookingRequestBase.RequiredInfo value) {
        this.requiredInfo = value;
    }

    /**
     * Gets the value of the specialRequirement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialRequirement() {
        return specialRequirement;
    }

    /**
     * Sets the value of the specialRequirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialRequirement(String value) {
        this.specialRequirement = value;
    }

    /**
     * Gets the value of the pickupPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickupPoint() {
        return pickupPoint;
    }

    /**
     * Sets the value of the pickupPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickupPoint(String value) {
        this.pickupPoint = value;
    }

    /**
     * Gets the value of the supplierNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierNote() {
        return supplierNote;
    }

    /**
     * Sets the value of the supplierNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierNote(String value) {
        this.supplierNote = value;
    }

    /**
     * Gets the value of the additionalRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link BookingRequestBase.AdditionalRemarks }
     *     
     */
    public BookingRequestBase.AdditionalRemarks getAdditionalRemarks() {
        return additionalRemarks;
    }

    /**
     * Sets the value of the additionalRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookingRequestBase.AdditionalRemarks }
     *     
     */
    public void setAdditionalRemarks(BookingRequestBase.AdditionalRemarks value) {
        this.additionalRemarks = value;
    }

    /**
     * Gets the value of the contactDetail property.
     * 
     * @return
     *     possible object is
     *     {@link BookingRequestBase.ContactDetail }
     *     
     */
    public BookingRequestBase.ContactDetail getContactDetail() {
        return contactDetail;
    }

    /**
     * Sets the value of the contactDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookingRequestBase.ContactDetail }
     *     
     */
    public void setContactDetail(BookingRequestBase.ContactDetail value) {
        this.contactDetail = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Remark" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "remark"
    })
    public static class AdditionalRemarks {

        @XmlElement(name = "Remark")
        protected List<String> remark;

        /**
         * Gets the value of the remark property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the remark property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRemark().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getRemark() {
            if (remark == null) {
                remark = new ArrayList<String>();
            }
            return this.remark;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ContactType">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="MOBILE"/>
     *               &lt;enumeration value="ALTERNATE"/>
     *               &lt;enumeration value="EMAIL"/>
     *               &lt;enumeration value="NOT_CONTACTABLE"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ContactName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ContactValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contactType",
        "contactName",
        "contactValue"
    })
    public static class ContactDetail {

        @XmlElement(name = "ContactType", required = true)
        protected String contactType;
        @XmlElement(name = "ContactName", required = true)
        protected String contactName;
        @XmlElement(name = "ContactValue", required = true)
        protected String contactValue;

        /**
         * Gets the value of the contactType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactType() {
            return contactType;
        }

        /**
         * Sets the value of the contactType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactType(String value) {
            this.contactType = value;
        }

        /**
         * Gets the value of the contactName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactName() {
            return contactName;
        }

        /**
         * Sets the value of the contactName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactName(String value) {
            this.contactName = value;
        }

        /**
         * Gets the value of the contactValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactValue() {
            return contactValue;
        }

        /**
         * Sets the value of the contactValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactValue(String value) {
            this.contactValue = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Inclusion" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "inclusion"
    })
    public static class Inclusions {

        @XmlElement(name = "Inclusion")
        protected List<String> inclusion;

        /**
         * Gets the value of the inclusion property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the inclusion property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInclusion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getInclusion() {
            if (inclusion == null) {
                inclusion = new ArrayList<String>();
            }
            return this.inclusion;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Question" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="QuestionText" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="QuestionAnswer" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "question"
    })
    public static class RequiredInfo {

        @XmlElement(name = "Question")
        protected List<BookingRequestBase.RequiredInfo.Question> question;

        /**
         * Gets the value of the question property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the question property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getQuestion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BookingRequestBase.RequiredInfo.Question }
         * 
         * 
         */
        public List<BookingRequestBase.RequiredInfo.Question> getQuestion() {
            if (question == null) {
                question = new ArrayList<BookingRequestBase.RequiredInfo.Question>();
            }
            return this.question;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="QuestionText" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="QuestionAnswer" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "questionText",
            "questionAnswer"
        })
        public static class Question {

            @XmlElement(name = "QuestionText", required = true)
            protected String questionText;
            @XmlElement(name = "QuestionAnswer", required = true)
            protected String questionAnswer;

            /**
             * Gets the value of the questionText property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getQuestionText() {
                return questionText;
            }

            /**
             * Sets the value of the questionText property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setQuestionText(String value) {
                this.questionText = value;
            }

            /**
             * Gets the value of the questionAnswer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getQuestionAnswer() {
                return questionAnswer;
            }

            /**
             * Sets the value of the questionAnswer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setQuestionAnswer(String value) {
                this.questionAnswer = value;
            }

        }

    }

}
