//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.12 at 12:48:55 PM PST 
//


package co.launchable.api.viator.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Holds the language code and options of  the product (Tour) / product options (Tour option).
 *             
 * 
 * <p>Java class for BookingLanguage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BookingLanguage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LanguageCode" type="{http://toursgds.com/api/01}languageCode"/>
 *         &lt;element name="LanguageOption" type="{http://toursgds.com/api/01}languageOption"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BookingLanguage", propOrder = {
    "languageCode",
    "languageOption"
})
public class BookingLanguage {

    @XmlElement(name = "LanguageCode", required = true)
    protected String languageCode;
    @XmlElement(name = "LanguageOption", required = true)
    protected LanguageOption languageOption;

    /**
     * Gets the value of the languageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageCode() {
        return languageCode;
    }

    /**
     * Sets the value of the languageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageCode(String value) {
        this.languageCode = value;
    }

    /**
     * Gets the value of the languageOption property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageOption }
     *     
     */
    public LanguageOption getLanguageOption() {
        return languageOption;
    }

    /**
     * Sets the value of the languageOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageOption }
     *     
     */
    public void setLanguageOption(LanguageOption value) {
        this.languageOption = value;
    }

}
