//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.12 at 12:48:55 PM PST 
//


package co.launchable.api.viator.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CancellationTransactionStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CancellationTransactionStatus">
 *   &lt;complexContent>
 *     &lt;extension base="{http://toursgds.com/api/01}TransactionStatus">
 *       &lt;sequence>
 *         &lt;element name="RejectionReason" type="{http://toursgds.com/api/01}cancellationRejectionReason" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CancellationTransactionStatus", propOrder = {
    "rejectionReason"
})
public class CancellationTransactionStatus
    extends TransactionStatus
{

    @XmlElement(name = "RejectionReason")
    protected CancellationRejectionReason rejectionReason;

    /**
     * Gets the value of the rejectionReason property.
     * 
     * @return
     *     possible object is
     *     {@link CancellationRejectionReason }
     *     
     */
    public CancellationRejectionReason getRejectionReason() {
        return rejectionReason;
    }

    /**
     * Sets the value of the rejectionReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link CancellationRejectionReason }
     *     
     */
    public void setRejectionReason(CancellationRejectionReason value) {
        this.rejectionReason = value;
    }

}
