//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.12 at 12:48:55 PM PST 
//


package co.launchable.api.viator.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://toursgds.com/api/01}Request">
 *       &lt;sequence>
 *         &lt;element name="BookingDateFrom" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="BookingDateTo" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="TravelDateFrom" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="TravelDateTo" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bookingDateFrom",
    "bookingDateTo",
    "travelDateFrom",
    "travelDateTo"
})
@XmlRootElement(name = "ManifestRequest")
public class ManifestRequest
    extends Request
{

    @XmlElement(name = "BookingDateFrom")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar bookingDateFrom;
    @XmlElement(name = "BookingDateTo")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar bookingDateTo;
    @XmlElement(name = "TravelDateFrom")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar travelDateFrom;
    @XmlElement(name = "TravelDateTo")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar travelDateTo;

    /**
     * Gets the value of the bookingDateFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBookingDateFrom() {
        return bookingDateFrom;
    }

    /**
     * Sets the value of the bookingDateFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBookingDateFrom(XMLGregorianCalendar value) {
        this.bookingDateFrom = value;
    }

    /**
     * Gets the value of the bookingDateTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBookingDateTo() {
        return bookingDateTo;
    }

    /**
     * Sets the value of the bookingDateTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBookingDateTo(XMLGregorianCalendar value) {
        this.bookingDateTo = value;
    }

    /**
     * Gets the value of the travelDateFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTravelDateFrom() {
        return travelDateFrom;
    }

    /**
     * Sets the value of the travelDateFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTravelDateFrom(XMLGregorianCalendar value) {
        this.travelDateFrom = value;
    }

    /**
     * Gets the value of the travelDateTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTravelDateTo() {
        return travelDateTo;
    }

    /**
     * Sets the value of the travelDateTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTravelDateTo(XMLGregorianCalendar value) {
        this.travelDateTo = value;
    }

}
