//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.12 at 12:48:55 PM PST 
//


package co.launchable.api.viator.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RedemptionRequestType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RedemptionRequestType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="VerifyRedemption"/>
 *     &lt;enumeration value="Redemption"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RedemptionRequestType")
@XmlEnum
public enum RedemptionRequestType {

    @XmlEnumValue("VerifyRedemption")
    VERIFY_REDEMPTION("VerifyRedemption"),
    @XmlEnumValue("Redemption")
    REDEMPTION("Redemption");
    private final String value;

    RedemptionRequestType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RedemptionRequestType fromValue(String v) {
        for (RedemptionRequestType c: RedemptionRequestType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
