//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.12 at 12:48:55 PM PST 
//


package co.launchable.api.viator.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Contains traveller information for the booking.
 *             
 * 
 * <p>Java class for Traveller complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Traveller">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TravellerIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TravellerTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GivenName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Surname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AgeBand" type="{http://toursgds.com/api/01}ageBandType"/>
 *         &lt;element name="LeadTraveller" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Traveller", propOrder = {
    "travellerIdentifier",
    "travellerTitle",
    "givenName",
    "surname",
    "ageBand",
    "leadTraveller"
})
public class Traveller {

    @XmlElement(name = "TravellerIdentifier", required = true)
    protected String travellerIdentifier;
    @XmlElement(name = "TravellerTitle")
    protected String travellerTitle;
    @XmlElement(name = "GivenName", required = true)
    protected String givenName;
    @XmlElement(name = "Surname", required = true)
    protected String surname;
    @XmlElement(name = "AgeBand", required = true)
    protected AgeBandType ageBand;
    @XmlElement(name = "LeadTraveller")
    protected Boolean leadTraveller;

    /**
     * Gets the value of the travellerIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTravellerIdentifier() {
        return travellerIdentifier;
    }

    /**
     * Sets the value of the travellerIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTravellerIdentifier(String value) {
        this.travellerIdentifier = value;
    }

    /**
     * Gets the value of the travellerTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTravellerTitle() {
        return travellerTitle;
    }

    /**
     * Sets the value of the travellerTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTravellerTitle(String value) {
        this.travellerTitle = value;
    }

    /**
     * Gets the value of the givenName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGivenName() {
        return givenName;
    }

    /**
     * Sets the value of the givenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGivenName(String value) {
        this.givenName = value;
    }

    /**
     * Gets the value of the surname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurname() {
        return surname;
    }

    /**
     * Sets the value of the surname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurname(String value) {
        this.surname = value;
    }

    /**
     * Gets the value of the ageBand property.
     * 
     * @return
     *     possible object is
     *     {@link AgeBandType }
     *     
     */
    public AgeBandType getAgeBand() {
        return ageBand;
    }

    /**
     * Sets the value of the ageBand property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgeBandType }
     *     
     */
    public void setAgeBand(AgeBandType value) {
        this.ageBand = value;
    }

    /**
     * Gets the value of the leadTraveller property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLeadTraveller() {
        return leadTraveller;
    }

    /**
     * Sets the value of the leadTraveller property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLeadTraveller(Boolean value) {
        this.leadTraveller = value;
    }

}
