//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.12 at 12:48:55 PM PST 
//


package co.launchable.api.viator.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnavailabilityReason.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UnavailabilityReason">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SOLD_OUT"/>
 *     &lt;enumeration value="BLOCKED_OUT"/>
 *     &lt;enumeration value="INACTIVE"/>
 *     &lt;enumeration value="PAST_CUTOFF_DATE"/>
 *     &lt;enumeration value="TRAVELLER_MISMATCH"/>
 *     &lt;enumeration value="NO_EVENT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "UnavailabilityReason")
@XmlEnum
public enum UnavailabilityReason {


    /**
     * 
     *                         When the product (Tour)/ product option (Tour Option) is sold out.
     *                     
     * 
     */
    SOLD_OUT,

    /**
     * 
     *                         When the product (Tour)/ product option (Tour Option) has been blocked out (not taking place on this date).
     *                     
     * 
     */
    BLOCKED_OUT,

    /**
     * 
     *                         When the product (Tour)/ product option (Tour Option) is no longer active.
     *                     
     * 
     */
    INACTIVE,

    /**
     * 
     *                         When the booking cut-off date has been reach for this product (Tour)/ product option (Tour Option).
     *                     
     * 
     */
    PAST_CUTOFF_DATE,

    /**
     * 
     *                         The tour grade requires a combination of travellers which does not
     *                         match the user's itinerary.
     *                     
     * 
     */
    TRAVELLER_MISMATCH,

    /**
     * 
     *                         When the required combination of travellers for this product (Tour)/ product option (Tour Option) is not met.
     *                     
     * 
     */
    NO_EVENT;

    public String value() {
        return name();
    }

    public static UnavailabilityReason fromValue(String v) {
        return valueOf(v);
    }

}
